end-to-end  precompiled gpu driver testing
Signed-off-by: shiva kumar <shivaku@nvidia.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -56,8 +56,36 @@ jobs:
         DRIVER_VERSIONS=$(grep '^DRIVER_VERSIONS ?=' versions.mk | awk -F' ?= ' '{print $2}')
         echo "DRIVER_VERSIONS=$DRIVER_VERSIONS" >> $GITHUB_ENV
         
-    - name: Validate gpu driver
+    # - name: Validate gpu driver
+    #   env:
+    #     TEST_CASE: "./tests/cases/nvidia-driver.sh"
+    #   run: |
+    #     sudo chmod 644 ${{ github.workspace }}/.cache/key
+    #     echo "${{ secrets.AWS_SSH_KEY }}" > ${private_key} && chmod 400 ${private_key}
+    #     rc=0
+    #     for driver_version in ${DRIVER_VERSIONS}; do
+    #       echo "Running e2e for DRIVER_VERSION=$driver_version"
+    #       ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} || status=$?
+    #       if [ $status -ne 0 ]; then
+    #         echo "e2e validation failed for driver version $driver_version with status $status"
+    #         rc=$status
+    #       fi
+    #     done
+    #     source ./tests/scripts/.definitions.sh
+    #     ./tests/scripts/pull.sh ${LOG_DIR} logs
+    #     exit $rc
+
+    # - name: Archive test logs
+    #   if: ${{ failure() }}
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: nvidiadriver-e2e-test-logs
+    #     path: ./logs/
+    #     retention-days: 15  
+
+    - name: Precompiled e2e test- upgrade kernel and Validate gpu driver
       env:
+        TEST_CASE_KERNEL_UPGRADE: "./tests/cases/nvidia-kernel-upgrade.sh"
         TEST_CASE: "./tests/cases/nvidia-driver.sh"
       run: |
         sudo chmod 644 ${{ github.workspace }}/.cache/key
@@ -65,20 +93,31 @@ jobs:
         rc=0
         for driver_version in ${DRIVER_VERSIONS}; do
           echo "Running e2e for DRIVER_VERSION=$driver_version"
-          ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} || status=$?
+          # SHIVA
+          export SSH_RETRY="0"
+          # ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} ${SSH_RETRY} || status=$?
+          ./tests/ci-run-e2e.sh ${TEST_CASE_KERNEL_UPGRADE} ${driver_version} ${SSH_RETRY} || status=$?
           if [ $status -ne 0 ]; then
-            echo "e2e validation failed for driver version $driver_version with status $status"
+            echo "Kernel upgrade failed"
             rc=$status
+          else
+            # system rebooted enable ssh retry
+            export SSH_RETRY="1"
+            ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} ${SSH_RETRY} || status=$?
+            if [ $status -ne 0 ]; then
+              echo "e2e validation failed for driver version $driver_version with status $status"
+              rc=$status
+            fi
           fi
         done
         source ./tests/scripts/.definitions.sh
         ./tests/scripts/pull.sh ${LOG_DIR} logs
         exit $rc
-
+    
     - name: Archive test logs
       if: ${{ failure() }}
       uses: actions/upload-artifact@v4
       with:
-        name: nvidiadriver-e2e-test-logs
+        name: nvidiadriver-Precompiled-e2e-test-logs
         path: ./logs/
         retention-days: 15  
